#!/bin/bash

DEBUG=0
DRYRUN=0
DRYRUN_SWITCH=""

BASE_DIR=$(dirname $0)
cd $BASE_DIR
BASE_DIR=$(pwd)

HOMEDIR=$HOME

show_usage() {
  echo "Usage: $(basename $0) [-d,--debug] [-n, --dry-run] [-h,--help] [-H,--home DIR]"
}

cprint() {
  COLOR=$1
  MSG=$2
  case $COLOR in
    black) COLOR_NUM=0 ;;
    red) COLOR_NUM=1 ;;
    green) COLOR_NUM=2 ;;
    yellow) COLOR_NUM=3 ;;
    blue) COLOR_NUM=4 ;;
    magenta) COLOR_NUM=5 ;;
    cyan) COLOR_NUM=6 ;;
    *) COLOR_NUM=7 ;; # white
  esac

  echo "$(tput setaf $COLOR_NUM)$MSG$(tput sgr 0)"
}

debug() {
  if [ $DEBUG -gt 0 ]; then
    cprint yellow "[DEBUG] $1"
  fi
}

check_and_replace() {
  FILE=$1
  TARGET=$2
  CHECK_AND_REPLACE_RET=0

  #
  # If $FILE alrady exist, create a backup
  #
  if [ -e $FILE ]; then
    
    #
    # If file is already a link, do nothing
    #

    if [ -L "$FILE" ] && [ $(readlink "$FILE") = "${TARGET}" ]; then
      cprint green "   * File ${FILE}: link is already present. Do nothing."
      return 0
    fi

    #
    # Otherwise, backup it
    #

    # Check for an available backup filename
    COUNT=0
    while [ $COUNT -eq 0 ] || [ -e "$BAK_FILE" ]; do
      BAK_FILE="${FILE}.bak-$(date +%Y-%m-%d)-${COUNT}"
      COUNT=$(($COUNT + 1))
    done

    # rename current file/dir
    [ -d $FILE ] && TYPE="directory" || TYPE="file"

    if [ $DRYRUN -eq 1 ]; then
      cprint blue "   * DRY-RUN MODE: would have created a backup of ${TYPE} \`$(basename ${FILE})\` -> \`$(basename ${BAK_FILE})\`"
      CHECK_AND_REPLACE_RET=1
    else
      debug "mv \"${FILE}\" \"${BAK_FILE}\""
      mv "${FILE}" "${BAK_FILE}"
      if [ $? -eq 0 ]; then
        cprint green "   * Created a backup of ${TYPE} \`$(basename ${FILE})\` -> \`$(basename ${BAK_FILE})\`"
      else 
        cprint red "   ! Error during backup creation. Abort."
        return 2
      fi
    fi
    
  fi

  #
  # Create the symbolic link
  #
  if [ $DRYRUN -eq 1 ]; then
    cprint blue "   * DRY-RUN MODE: would have created link: ${FILE} -> ${TARGET}"
    CHECK_AND_REPLACE_RET=1
  else
    debug "ln -s \"${TARGET}\" \"${FILE}\""
    ln -s "${TARGET}" "${FILE}"
    if [ $? -eq 0 ]; then
      cprint green "   * Created link: ${FILE} -> ${TARGET}"
    else
      cprint red "   ! Error during link creation. Abort."
      return 2
    fi
  fi

  return $CHECK_AND_REPLACE_RET
}


bootstrap_module() {
  MODULE=$1

  BOOTSTRAP_MODULE_RET=0
  IFS=$'\r\n'
  for line in $(cat $MODULE/.bootstrap | grep -Ev '^\s*#'); do
    FILE=$(echo $line | awk '{print $1}')
    TARGET=$(echo $line | awk '{print $2}')

    cprint magenta " * Processing file $(basename $FILE)"

    # If target is empty, there is an error
    if [ -z "${TARGET}" ]; then
      cprint red "   ! Target is empty. Did you forget it?"
      return 2
    fi
    # If target is a dash, deduct it
    if [ "${TARGET}" = "-" ]; then
      TARGET=$(expr $(basename "${FILE}") : '^\.*\(.*\)$')
    fi

    # Add parent dir of target
    TARGET="${BASE_DIR}/${MODULE}/$TARGET"

    # File is always in homedir
    FILE="$HOMEDIR/$FILE"

    cprint cyan "   % Target is ${TARGET}"

    # Check that target exist
    if [ ! -e "${TARGET}" ]; then
      cprint red "   ! Error: target does not exist ($TARGET)"
      BOOTSTRAP_MODULE_RET=2
      continue
    fi 

    check_and_replace $FILE $TARGET
    BOOTSTRAP_MODULE_RET2=$?

    # Higher return code, means higher error
    if [[ $BOOTSTRAP_MODULE_RET2 -gt $BOOTSTRAP_MODULE_RET ]]; then
      BOOTSTRAP_MODULE_RET=$BOOTSTRAP_MODULE_RET2
    fi
  done

  return $BOOTSTRAP_MODULE_RET
}

#
# Main script
#

# Get arguments
getopt -T > /dev/null 2>&1
if [ $? -eq 4 ]; then
  # GNU enhanced getopt is available
  OPTS=$(getopt -o dhnH: --long debug,help,dry-run,home -n "$(basename $0)" -- "$@")
  echo $OPTS
  eval set -- "$OPTS"

  while true; do
    echo "\$1 = $1"
    case "$1" in
      -H|--home) HOMEDIR=$2 ; shift 2 ;;
      -d|--debug) DEBUG=1 ;;
      -n|--dry-run) DRYRUN=1 ; DRYRUN_SWITCH="-n" ; shift ;;
      -h|--help) show_usage ; exit 0 ;;
      --) shift ; break ;;
      *) echo "Internal error!"; exit 1 ;;
    esac
  done
else
  # Original getopt is available. So use getopts instead
  while getopts ":dhnH:" OPT; do
    case "$OPT" in
      H) HOMEDIR=$OPTARG ;;
      d) DEBUG=1 ;;
      n) DRYRUN=1 ; DRYRUN_SWITCH="-n" ;;
      h) show_usage ; exit 0 ;;
      \?) echo "Invalid option: -$OPTARG" >&2 ; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument." >&2 ; exit 1 ;;
    esac
  done
fi


ERRORS=0
CHANGES_TO_APPLY=0

# For each submodule, read .bootstrap file and do the bootstrap magic
for module in $(ls .); do
  if [ "$module" = "." ] || [ "$module" = ".." ]; then
    continue
  fi


  if [ -d "$module" ]; then
    cprint cyan "[ Entering in submodule : $(basename $module) ]"

    SUCCESS=0
    LOCAL_CHANGES_TO_APPLY=0
    # Execute standard boostrap if .bootstrap file exists
    if [ -f $module/.bootstrap ]; then
      cprint cyan "% Calling standard bootstrap"
      bootstrap_module $module
      RET=$?
      if [ $RET -eq 0 ]; then
        SUCCESS=1
      elif [ $RET -eq 1 ]; then
        SUCCESS=1
        LOCAL_CHANGES_TO_APPLY=1
      else 
        ERRORS=1
        cprint red "*** Some errors occured during standard bootstrap. Please review. ***"
        echo
        continue
      fi
    fi

    # Execute custom bootstrap if a bootstrap script exists
    if [ -x $module/bootstrap ]; then
      cprint cyan "% Executing custom bootstrap script"
      $module/bootstrap $DRYRUN_SWITCH
      RET=$?
      if [ $RET -eq 0 ]; then
        SUCCESS=1
      elif [ $RET -eq 1 ]; then
        SUCCESS=1
        LOCAL_CHANGES_TO_APPLY=1
      else 
        ERRORS=1
        cprint red "*** Some errors occured during custom bootstrap. Please review. ***"
        echo
        continue
      fi
    fi

    if [ $SUCCESS -eq 0 ]; then
      cprint yellow "*** No bootstrap found in module ***"
    elif [ $LOCAL_CHANGES_TO_APPLY -eq 1 ]; then
      cprint cyan "*** There are changes to be applyed ***"
      CHANGES_TO_APPLY=1
    else
      cprint green "*** Module has been successfully bootstraped ***"
    fi
    echo
  fi
done

if [[ $CHANGES_TO_APPLY -eq 1 ]]; then
  exit 1
elif [[ $ERRORS -eq 1 ]]; then
  exit 2
fi

exit 0
