execute pathogen#infect()

" let g:solarized_termcolors=256

" Auto-correction configuration
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"Airline theme configuration (use Solarized)
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1

" Space and tab management configuration
set expandtab
set tabstop=2
retab
set shiftwidth=2
filetype plugin indent on

" Display configuration
syntax enable
set background=dark
colorscheme solarized
set number
set colorcolumn=81


" Have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" Bash-style tab completion for files
set wildmenu
set wildmode=longest:full,full

" Correct issue when pasting from one file to another
set clipboard=unnamed

" Adjust size of copy/paste buffer
set viminfo='20,<1000,s1000
