#!/bin/bash

cprint() {
  COLOR=$1
  MSG=$2
  case $COLOR in
    black) COLOR_NUM=0 ;;
    red) COLOR_NUM=1 ;;
    green) COLOR_NUM=2 ;;
    yellow) COLOR_NUM=3 ;;
    blue) COLOR_NUM=4 ;;
    magenta) COLOR_NUM=5 ;;
    cyan) COLOR_NUM=6 ;;
    *) COLOR_NUM=7 ;; # white
  esac

  echo "$(tput setaf $COLOR_NUM)$MSG$(tput sgr 0)"
}

# Ensure .zshrc is a file
cprint magenta " * Ensure .zshrc is a regular file"
if [ -f ~/.zshrc ] && [ ! -h ~/.zshrc ]; then
  cprint green "   * .zshrc is a regular file"
else
  EXT=".bak-$(date +%Y.%m.%d-%H.%M.%S)"
  cprint cyan "   % .zshrc is not a regular file. Backup to .zshrc${EXT}"
  mv ~/.zshrc ~/.zshrc${EXT}
  touch ~/.zshrc
  cprint green "   * Link .zshrc moved and replaced with a regular file"
fi

# Ensure that file .zshrc.custom is sourced in .zshrc
# Only if .zshrc is a file.

cprint magenta " * Ensure we source .zshrc.custom in .zshrc"
if [ -f ~/.zshrc ] && [ ! -h ~/.zshrc ]; then
  if ! grep -qE '\$HOME/\.zshrc\.custom' ~/.zshrc; then
    cprint yellow "  * Adding source to .zshrc.custom in .zshrc file."
    echo "source \$HOME/.zshrc.custom" >> ~/.zshrc
  else
    cprint green "   * Source to .zshrc.custom is already set. Nothing to do."
  fi
else
  # Should not happen
  cprint red "   * .zshrc is not a regular file. Do nothing."
fi

check_and_replace() {
	FILE="$1"
	TARGET="$2"

	if [[ -L "$FILE" ]] && [[ $(readlink "$FILE") == "$TARGET" ]]; then
		cprint green "$FILE: link already present"
	else
		mv $FILE $FILE.bak-$(date +%Y-%m-%d-%H-%M-%S)
		ln -s "$TARGET" "$FILE"
		cprint green "Created link $FILE -> $TARGET"
	fi

}

cprint magenta "* Installing zim"

check_and_replace ~/.zim $(pwd)/zim
check_and_replace ~/.zimrc $(pwd)/zimrc

cprint magenta "* Installing zsh configuration"
check_and_replace ~/.zshrc.custom $(pwd)/zshrc.custom
check_and_replace ~/.zshenv $(pwd)/zshenv
check_and_replace ~/.zprofile $(pwd)/zprofile

echo "Installation done. Running zsh now"
exec zsh
